### ISSUE TITLE
{{#each P.Player}}

### ISSUE THREAD

**Issue by Doxramos** [GitHub-TC/EmpyrionLCDInfo#1]
Awesome looking mod! Unfortunately for me I've got it in the content/mods directory, but when I boot up the server I don't see any realtime information. Any ideas or dependancies that need to be met?

**Comment by GitHub-TC** [comment]
> Awesome looking mod! Unfortunately for me I've got it in the content/mods directory, but when I boot up the server I don't see any realtime information. Any ideas or dependancies that need to be met?

Do you only extract the ZIP file in your Content\Mod folder? And what about the EGS Logs, there must be in the Playfieldlogs !!! like
05-18:24:35.482 20_24 -LOG- Loaded Mod 'EmpyrionLCDInfo' (Version: 1.0.10) from folder EmpyrionLCDInfo

**Comment by Doxramos** [comment]
And maybe; the old steam dedicated was running instead of the steamcmd version. Amazing mod! Thanks man.
